### ISSUE TITLE
关于BatchNorm

### ISSUE THREAD

**Issue by fucker255** [pkqbajng/CGFormer#10]
作者您好，我在使用您的代码进行训练的时候发现在Mono_DepthNet_modules.py中对mlp_input的处理中使用了Batchnorm，但训练咋你这里报错，表示batchsize=1有问题。我是使用的单卡训练，并且代码中有提示batchsize只能为1，同时也不是使用的SyncBatchnorm，请问这是为什么。

**Comment by fucker255** [comment]
把两个mlp_input的batchnorm注释掉之后就能成功训练了

**Comment by Samsara011** [comment]
Hello, I also encountered the same problem, do you have a specific solution？

**Comment by fucker255** [comment]
> Hello, I also encountered the same problem, do you have a specific solution？

In Mono_DepthNet_modules.py there are 2 Batchnorm used for mlp_input, one in depth_net and the other in ASPP. I just simply comment them out and training could be started, but I doubt if it's reasonable.

**Comment by pkqbajng** [comment]
> 作者您好，我在使用您的代码进行训练的时候发现在Mono_DepthNet_modules.py中对mlp_input的处理中使用了Batchnorm，但训练咋你这里报错，表示batchsize=1有问题。我是使用的单卡训练，并且代码中有提示batchsize只能为1，同时也不是使用的SyncBatchnorm，请问这是为什么。

单卡训练的时候，整体的bs是1，是不能做bn的，但使用多卡的时候，如果是distributed的方式训练，就不会遇到这个问题。这个mlp是为了将相机内外参引入depth和context的估计，把batchnorm换成其他的比如group norm等等应该也是ok的，影响不会很大

**Comment by fucker255** [comment]
> thanks,I tried, but reported another error; Can I ask you about the configuration of your training equipment?

just the original semantickitti_CGFormer.py. You may have not commented the init of bn here:
![屏幕截图 2024-11-01 162800](https://github.com/user-attachments/assets/f9162636-dd2a-43d6-9f62-52099b04d1dc)

**Comment by fucker255** [comment]
> > 作者您好，我在使用您的代码进行训练的时候发现在Mono_DepthNet_modules.py中对mlp_input的处理中使用了Batchnorm，但训练咋你这里报错，表示batchsize=1有问题。我是使用的单卡训练，并且代码中有提示batchsize只能为1，同时也不是使用的SyncBatchnorm，请问这是为什么。
> 
> 单卡训练的时候，整体的bs是1，是不能做bn的，但使用多卡的时候，如果是distributed的方式训练，就不会遇到这个问题。这个mlp是为了将相机内外参引入depth和context的估计，把batchnorm换成其他的比如group norm等等应该也是ok的，影响不会很大

好的，谢谢你，我理解了，还是对分布式训练不够熟悉

**Comment by pkqbajng** [comment]
> > > 作者您好，我在使用您的代码进行训练的时候发现在Mono_DepthNet_modules.py中对mlp_input的处理中使用了Batchnorm，但训练咋你这里报错，表示batchsize=1有问题。我是使用的单卡训练，并且代码中有提示batchsize只能为1，同时也不是使用的SyncBatchnorm，请问这是为什么。
> > 
> > 
> > 单卡训练的时候，整体的bs是1，是不能做bn的，但使用多卡的时候，如果是distributed的方式训练，就不会遇到这个问题。这个mlp是为了将相机内外参引入depth和context的估计，把batchnorm换成其他的比如group norm等等应该也是ok的，影响不会很大
> 
> 好的，谢谢你，我理解了，还是对分布式训练不够熟悉
没有这个bn应该影响不大，我忙完这阵重新训一个试下

**Comment by fucker255** [comment]
OK，我目前也在训这个

**Comment by fucker255** [comment]
好的，辛苦你
