### ISSUE TITLE
Test on nuScenes

### ISSUE THREAD

**Issue by wwwwwxinshou** [pkqbajng/CGFormer#12]
Thank you for your excellent work！Is there any result on the nuScenes dataset? Why not test on this dataset?

**Comment by pkqbajng** [comment]
> Thank you for your excellent work！Is there any result on the nuScenes dataset? Why not test on this dataset?

We don't have enough GPUs prevously so that we mainly conduct experiments on the monocular setting. We'll update this results in the following CGFormer++.
