### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by qiuxiam** [pkqbajng/CGFormer#13]
Hou to genarate the depth/sequences/
![屏幕截图 2024-11-29 203444](https://github.com/user-attachments/assets/10e6bb18-5e90-437b-bda4-0d4a33709ef9)

**Comment by pkqbajng** [comment]
Hi, we've updated the scripts, please refer to the preprocess folder.

**Comment by qiuxiam** [comment]
When I run the image2depth_kitti360.sh, I get a problem, is it a problem with the dataset?
![屏幕截图 2024-12-05 112538](https://github.com/user-attachments/assets/2df64f0d-8949-4153-996a-c8868cee3fb1)

**Comment by qiuxiam** [comment]
> 您好，我们已经更新了脚本，请参考 preprocess 文件夹。

When I run the image2depth_kitti360.sh, I get a problem, is it a problem with the dataset?
![Uploading 屏幕截图 2024-12-05 112538.png…]()

**Comment by qiuxiam** [comment]
> 您好，我们已经更新了脚本，请参考 preprocess 文件夹。

When I run the image2depth_kitti360.sh, I get a problem, is it a problem with the dataset?
![屏幕截图 2024-12-05 112538](https://github.com/user-attachments/assets/2a36d8f6-db39-449b-beb6-8369f1d82ea8)

**Comment by pkqbajng** [comment]
> > 您好，我们已经更新了脚本，请参考 preprocess 文件夹。
> 
> When I run the image2depth_kitti360.sh, I get a problem, is it a problem with the dataset? ![屏幕截图 2024-12-05 112538](https://private-user-images.githubusercontent.com/152238990/392663884-2a36d8f6-db39-449b-beb6-8369f1d82ea8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODM4MjMsIm5iZiI6MTczMzM4MzUyMywicGF0aCI6Ii8xNTIyMzg5OTAvMzkyNjYzODg0LTJhMzZkOGY2LWRiMzktNDQ5Yi1iZWI2LTgzNjlmMWQ4MmVhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwNzI1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTVjY2JkZmI3ZmIwMWQzODlhMTk1YmQxYzVmMDc1NDQ5ZGRkMmFmMDI3Yjg5YzdjZDM3ODk1MGE4ZjRiMzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0yfcaySU2O9c4_qolSouVAW4zqnthyPxLSQVj3aJYaE)

The max length for sequence 2013_05_28_drive_0002_sync is 011226. There seems no problem
