### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by VitaLemonTea1** [pkqbajng/CGFormer#3]
Hi,
Thanks for releasing code, this is a great work! After I installed dataset according to dataset.md, I found that lidarseg was not installed, but the code could run correctly. May I ask where lidarseg was used.

**Comment by pkqbajng** [comment]
Hi, lidarseg is used for pretraining the backbone, including encoder, context net and depth net, which can improve the convergence speed. This strategy is also employed in [FBBEV](https://github.com/NVlabs/FB-BEV and [MonoOcc](https://github.com/ucaszyp/MonoOcc)

**Comment by pkqbajng** [comment]
Close as completed. Open it if having other questions.

**Comment by Samsara011** [comment]
@pkqbajng 
Hello, author! Thank you for your excellent work. I also completed the dataset preparation according to the steps of dataset.md, but I found that the lidarseg part was missing, may I ask how it was generated? thank you

**Comment by pkqbajng** [comment]
> @pkqbajng Hello, author! Thank you for your excellent work. I also completed the dataset preparation according to the steps of dataset.md, but I found that the lidarseg part was missing, may I ask how it was generated? thank you

![image](https://github.com/user-attachments/assets/a4335069-a475-4202-9696-0bbc77ab6189)
You can download it from [here](https://www.semantic-kitti.org/dataset.html#download)

**Comment by Samsara011** [comment]
@pkqbajng 
Okay, I understand. Thank you very much
