### ISSUE TITLE
关于训练中的epoch

### ISSUE THREAD

**Issue by lcl124252** [pkqbajng/CGFormer#4]
非常感谢你们的工作，我在论文中看到你们是训练了25个epoch，但是在配置文件中，只有training_steps=25000这个参数，而在kitti360中是54000，我想问一下epoch是根据这个steps算出来的吗？如果我想训练其他数据集，我应该怎么去得到一个epoch中的steps？

**Comment by pkqbajng** [comment]
> 非常感谢你们的工作，我在论文中看到你们是训练了25个epoch，但是在配置文件中，只有training_steps=25000这个参数，而在kitti360中是54000，我想问一下epoch是根据这个steps算出来的吗？如果我想训练其他数据集，我应该怎么去得到一个epoch中的steps？

假设你数据集的长度为5000，以batch size=4训练，则一个epoch是1250个iteration，如果训练25个epoch，则最后的training_steps就是25 * 1250=31250，训练的时候设置一个在此附近的值即可
