### ISSUE TITLE
非常感谢你们的工作，请问可以公布你们的可视化代码吗？

### ISSUE THREAD

**Issue by lcl124252** [pkqbajng/CGFormer#6]
非常感谢你们的工作，我在可视化方面遇到了一些问题，官方的API貌似不可以固定视角，但是我看你们的可视化图是有一个摄像机视角的标志，请问你们可以公布一下你们的可视化代码吗？非常感谢！

**Comment by pkqbajng** [comment]
Apologize for replying so late. I have been occupied with the coming conference. I will try to update the entire project by the end of November.

**Comment by lcl124252** [comment]
> Apologize for replying so late. I have been occupied with the coming conference. I will try to update the entire project by the end of November.

非常感谢你的回复，祝愿你能在会议中取得好的结果。

**Comment by pkqbajng** [comment]
> > Apologize for replying so late. I have been occupied with the coming conference. I will try to update the entire project by the end of November.
> 
> 非常感谢你的回复，祝愿你能在会议中取得好的结果。

感谢，也祝您研究顺利

**Comment by pkqbajng** [comment]
> 非常感谢你们的工作，我在可视化方面遇到了一些问题，官方的API貌似不可以固定视角，但是我看你们的可视化图是有一个摄像机视角的标志，请问你们可以公布一下你们的可视化代码吗？非常感谢！

您好，可视化代码已开源，在tools/visualize.py下面
