### ISSUE TITLE
Hi, why I need to use velodyne data?

### ISSUE THREAD

**Issue by DianJJ** [pkqbajng/CGFormer#7]
Hi, thanks for the code. I try to train the model and it keeps telling me that I miss velodyne data, why do I need this file?

![屏幕截图 2024-10-10 185035](https://github.com/user-attachments/assets/8b16bdad-e748-4300-a70b-fc5c8492ba1a)

**Comment by pkqbajng** [comment]
The depth map for depth supervision is obtained by projecting the velodyne data to the image plane.

**Comment by pkqbajng** [comment]
Reopen this issue for other questions.

**Comment by DianJJ** [comment]
It needs extra lidar data to train?

**Comment by pkqbajng** [comment]
> It needs extra lidar data to train?

Yeah, the lidar data with semantic label is employed to generate dense occupancy ground truth, while the naive lidar can be adopted to generate depth map, as done in the [BEVDepth](https://github.com/Megvii-BaseDetection/BEVDepth), [OpenOccupancy](https://github.com/JeffWang987/OpenOccupancy)
