### ISSUE TITLE
Regarding the issue of using CodaLab for the SemanticKitti dataset evaluation.

### ISSUE THREAD

**Issue by YuEn-git** [pkqbajng/CGFormer#8]
Thank you very much for your outstanding work ！We hope to build upon it for further improvements. 
However, recently we encountered an issue while submitting the test results of SemanticKitti on CodaLab. After clicking the Submit button, the process gets stuck, and we are unable to upload the .zip file. Have you experienced this issue before? Looking forward to your response.

**Comment by pkqbajng** [comment]
> Thank you very much for your outstanding work ！We hope to build upon it for further improvements. However, recently we encountered an issue while submitting the test results of SemanticKitti on CodaLab. After clicking the Submit button, the process gets stuck, and we are unable to upload the .zip file. Have you experienced this issue before? Looking forward to your response.

Hi, I didn't encounter this issue when I submitted the results. Could you provide a screenshot?

**Comment by pkqbajng** [comment]
> Thank you very much for your outstanding work ！We hope to build upon it for further improvements. However, recently we encountered an issue while submitting the test results of SemanticKitti on CodaLab. After clicking the Submit button, the process gets stuck, and we are unable to upload the .zip file. Have you experienced this issue before? Looking forward to your response.

Hi, I resubmitted the result and it gets stuck, too. I speculate the coming CVPR deadline leads the crash of the server.
