### ISSUE TITLE
Pretrain depth model

### ISSUE THREAD

**Issue by 3bobo** [pkqbajng/CGFormer#9]
Thanks for your work! I notice that in the config file, the model need to first load a pretrain depth model as `load_from = './pretrain/pretrain_geodepth.pth'`, but I do not find the details of the pre-train training and model details in the paper, so could you provide the architecture detail of the pre-train geodepth model and how to pre-train the geodepth model?

**Comment by pkqbajng** [comment]
> Thanks for your work! I notice that in the config file, the model need to first load a pretrain depth model as `load_from = './pretrain/pretrain_geodepth.pth'`, but I do not find the details of the pre-train training and model details in the paper, so could you provide the architecture detail of the pre-train geodepth model and how to pre-train the geodepth model?

Hi, please refer to this [issue](https://github.com/pkqbajng/CGFormer/issues/3#issuecomment-2202756412). The pretraining process is similar to the FB-Occ. I'll update the overall project to include this part of code at the end of November.

**Comment by pkqbajng** [comment]
Close as completed. Reopen this issue if have further questions

**Comment by 3bobo** [comment]
Thanks!

**Comment by pkqbajng** [comment]
> Thanks for your work! I notice that in the config file, the model need to first load a pretrain depth model as `load_from = './pretrain/pretrain_geodepth.pth'`, but I do not find the details of the pre-train training and model details in the paper, so could you provide the architecture detail of the pre-train geodepth model and how to pre-train the geodepth model?

We've updated the pretraining script.
